[options]
HoldPkg     = pacman glibc
Architecture = auto

Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

[artix]
Server = https://mirrors.artixlinux.org/artix/os/$arch
SigLevel = Optional TrustAll

[system]
Server = https://mirrors.artixlinux.org/system/os/$arch
SigLevel = Optional TrustAll

[world]
Server = https://mirrors.artixlinux.org/world/os/$arch
SigLevel = Optional TrustAll

[galaxy]
Server = https://mirrors.artixlinux.org/galaxy/os/$arch
SigLevel = Optional TrustAll

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
