# Фикс для черного экрана в виртуалках (UTM SE, VirtualBox без 3D)
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = LIBGL_ALWAYS_SOFTWARE,1
env = WLR_NO_HARDWARE_CURSORS,1
env = XDG_SESSION_TYPE,wayland

exec-once = hyprpaper
exec-once = kitty -e bash /usr/local/bin/welcome

# Базовые бинды
bind = SUPER, Q, exec, kitty
bind = SUPER, M, exit,
