---
backend: pacman

pacman:
    num_retries: 2
    disable_download_timeout: true
    needed_only: true

update_db: true
update_system: false
skip_if_no_internet: true

operations:
    - remove:
        - calamares
