---
efiSystemPartition: "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file
drawNestedPartitions: false
alwaysShowPartitionLabels: true
defaultPartitionType: "gpt"
defaultFileSystemType: "ext4"
