---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - name: wheel
      must_exist: false
      system: true
    - audio

autologinGroup: autologin

doAutologin: false

sudoersGroup: wheel
sudoersConfigureWithGroup: true

setRootPassword: true
doReusePassword: true

passwordRequirements:
    minLength: 1
    maxLength: -1

allowWeakPasswords: true
allowWeakPasswordsDefault: true

setHostname: EtcFile
writeHostsFile: true

presets:
    fullName:
        editable: true
    loginName:
        editable: true
