---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - netinstall@desktops
    - netinstall
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - packages
    - shellprocess@okakos
    - bootloader
    - umount
  - show:
    - finished

branding: okakos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
