name: Build OkakOS ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm archiso base-devel

      - name: Prepare Archiso Profile
        run: |
          cp -r /usr/share/archiso/configs/releng ./okakos-profile
          
          cp -r airootfs ./okakos-profile/
          cp packages.x86_64 ./okakos-profile/packages.x86_64
          
          mkdir -p ./okakos-profile/airootfs/etc/systemd/system/basic.target.wants/
          ln -sf /etc/systemd/system/okakos67.service ./okakos-profile/airootfs/etc/systemd/system/basic.target.wants/okakos67.service

      - name: Build ISO
        run: |
          mkarchiso -v -w /tmp/archiso-tmp -o /tmp/out ./okakos-profile

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OkakOS-ISO
          path: /tmp/out/*.iso
          retention-days: 7
